# -*- coding: utf-8 -*-
"""3_spatial_analysis.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DiNegtglFOd0bZ6LUjrhtkkW76eU8Vss
"""

import streamlit as st
import pandas as pd
import plotly.express as px
from pathlib import Path


st.set_page_config(
    page_title="Spatial Patterns",
    layout="wide"
)


st.title("Spatial Patterns: Where Are the Main Activity Centers?")

st.markdown(
    """
    This section analyzes the spatial distribution of Citi Bike activity in the
    Jersey City / Hoboken system. The main goal is to identify where Citi Bike usage
    is most concentrated, which stations are the busiest, and whether activity clusters
    around major urban and transportation nodes.
    """
)


def assign_city_area(row):
    name = str(row["station_name"]).lower()
    lat = row["lat"]
    lng = row["lng"]

    hoboken_keywords = [
        "hoboken",
        "washington st",
        "clinton st",
        "hudson st",
        "river st",
        "shipyard",
        "church sq",
        "monroe st",
        "madison st",
        "columbus park",
        "mama johnson",
        "sinatra",
        "11 st",
        "8 st",
        "6 st & grand",
        "14 st ferry",
        "city hall - washington",
        "bloomfield",
        "grand st & 2 st",
        "adams st",
        "jackson st",
        "marshall st",
        "willow ave"
    ]

    if any(keyword in name for keyword in hoboken_keywords):
        return "Hoboken"

    if pd.notna(lat) and pd.notna(lng):
        if lat >= 40.735 and lng >= -74.045:
            return "Hoboken"

    return "Jersey City"


@st.cache_data
def load_uploaded_data(uploaded_files):
    df_list = []
    for file in uploaded_files:
        temp_df = pd.read_csv(file)
        df_list.append(temp_df)

    df = pd.concat(df_list, ignore_index=True)
    return df


@st.cache_data
def load_local_data():
    data_dir = Path("data")
    data_files = sorted(data_dir.glob("JC-2025*-citibike-tripdata.csv"))

    if len(data_files) == 0:
        return None

    df = pd.concat(
        [pd.read_csv(file) for file in data_files],
        ignore_index=True
    )
    return df


@st.cache_data
def clean_trip_data(df):
    df = df.copy()

    required_columns = [
        "started_at",
        "ended_at",
        "start_station_name",
        "start_station_id",
        "start_lat",
        "start_lng"
    ]

    missing_columns = [col for col in required_columns if col not in df.columns]

    if missing_columns:
        raise ValueError(f"Missing required columns: {missing_columns}")

    df["started_at"] = pd.to_datetime(df["started_at"], errors="coerce")
    df["ended_at"] = pd.to_datetime(df["ended_at"], errors="coerce")

    df["ride_duration_min"] = (
        df["ended_at"] - df["started_at"]
    ).dt.total_seconds() / 60

    df = df[
        (df["ride_duration_min"] > 0) &
        (df["ride_duration_min"] <= 24 * 60)
    ].copy()

    df = df.dropna(
        subset=[
            "start_station_name",
            "start_station_id",
            "start_lat",
            "start_lng"
        ]
    )

    return df


@st.cache_data
def build_station_activity(df):
    start_station_activity = (
        df.groupby(
            [
                "start_station_id",
                "start_station_name",
                "start_lat",
                "start_lng"
            ],
            dropna=False
        )
        .size()
        .reset_index(name="start_trips")
    )

    end_required_columns = [
        "end_station_id",
        "end_station_name",
        "end_lat",
        "end_lng"
    ]

    if all(col in df.columns for col in end_required_columns):
        end_station_activity = (
            df.dropna(
                subset=[
                    "end_station_id",
                    "end_station_name",
                    "end_lat",
                    "end_lng"
                ]
            )
            .groupby(
                [
                    "end_station_id",
                    "end_station_name",
                    "end_lat",
                    "end_lng"
                ],
                dropna=False
            )
            .size()
            .reset_index(name="end_trips")
        )

        station_activity = start_station_activity.merge(
            end_station_activity,
            left_on="start_station_id",
            right_on="end_station_id",
            how="outer"
        )

        station_activity["station_id"] = station_activity["start_station_id"].fillna(
            station_activity["end_station_id"]
        )

        station_activity["station_name"] = station_activity["start_station_name"].fillna(
            station_activity["end_station_name"]
        )

        station_activity["lat"] = station_activity["start_lat"].fillna(
            station_activity["end_lat"]
        )

        station_activity["lng"] = station_activity["start_lng"].fillna(
            station_activity["end_lng"]
        )

        station_activity["start_trips"] = station_activity["start_trips"].fillna(0)
        station_activity["end_trips"] = station_activity["end_trips"].fillna(0)

    else:
        station_activity = start_station_activity.copy()
        station_activity["station_id"] = station_activity["start_station_id"]
        station_activity["station_name"] = station_activity["start_station_name"]
        station_activity["lat"] = station_activity["start_lat"]
        station_activity["lng"] = station_activity["start_lng"]
        station_activity["end_trips"] = 0

    station_activity["total_trips"] = (
        station_activity["start_trips"] +
        station_activity["end_trips"]
    )

    station_activity = station_activity[
        [
            "station_id",
            "station_name",
            "lat",
            "lng",
            "start_trips",
            "end_trips",
            "total_trips"
        ]
    ].copy()

    station_activity["area"] = station_activity.apply(assign_city_area, axis=1)

    return station_activity


def build_area_activity(station_activity):
    area_activity = (
        station_activity
        .groupby("area", as_index=False)
        .agg(
            total_trips=("total_trips", "sum"),
            start_trips=("start_trips", "sum"),
            end_trips=("end_trips", "sum"),
            station_count=("station_id", "nunique")
        )
    )
    return area_activity


with st.sidebar:
    st.header("Data Input")

    uploaded_files = st.file_uploader(
        "Upload Citi Bike CSV files",
        type=["csv"],
        accept_multiple_files=True
    )

    st.markdown(
        """
        Upload one or more monthly Citi Bike CSV files.
        If no files are uploaded, the app will automatically try to read from the `data/` folder.
        """
    )


try:
    if uploaded_files:
        raw_df = load_uploaded_data(uploaded_files)
        data_source_label = "Uploaded CSV files"
    else:
        raw_df = load_local_data()
        data_source_label = "Local data folder"

    if raw_df is None:
        st.info(
            "Please upload Citi Bike CSV files in the sidebar, or place the monthly files inside the `data/` folder."
        )
        st.stop()

    df = clean_trip_data(raw_df)
    station_activity = build_station_activity(df)
    area_activity = build_area_activity(station_activity)

except Exception as e:
    st.error("The data could not be processed.")
    st.exception(e)
    st.stop()


with st.sidebar:
    st.header("Filters")

    area_options = sorted(station_activity["area"].dropna().unique())

    selected_areas = st.multiselect(
        "Select areas",
        options=area_options,
        default=area_options
    )

    trip_metric = st.selectbox(
        "Select trip metric",
        options=["total_trips", "start_trips", "end_trips"],
        index=0
    )

    top_n = st.slider(
        "Number of top stations",
        min_value=5,
        max_value=20,
        value=10,
        step=1
    )

    map_zoom = st.slider(
        "Map zoom",
        min_value=10.0,
        max_value=13.0,
        value=11.3,
        step=0.1
    )


filtered_station_activity = station_activity[
    station_activity["area"].isin(selected_areas)
].copy()

filtered_area_activity = build_area_activity(filtered_station_activity)

if filtered_station_activity.empty:
    st.warning("No stations match the selected filters.")
    st.stop()


st.subheader("Dataset Overview")

col1, col2, col3, col4, col5 = st.columns(5)

col1.metric("Data Source", data_source_label)
col2.metric("Total Trips", f"{len(df):,}")
col3.metric("Stations", f"{station_activity['station_id'].nunique():,}")
col4.metric("Areas", f"{station_activity['area'].nunique():,}")
col5.metric("Average Ride Duration", f"{df['ride_duration_min'].mean():.1f} min")


st.divider()


st.subheader("Chart 8. Interactive Station Activity Map")

fig8 = px.scatter_mapbox(
    filtered_station_activity,
    lat="lat",
    lon="lng",
    size=trip_metric,
    color="area",
    hover_name="station_name",
    hover_data={
        "area": True,
        "start_trips": ":,.0f",
        "end_trips": ":,.0f",
        "total_trips": ":,.0f",
        "lat": False,
        "lng": False
    },
    size_max=35,
    zoom=map_zoom,
    height=700,
    title="Chart 8. Interactive Station Activity Map: Jersey City / Hoboken Citi Bike Activity"
)

fig8.update_layout(
    mapbox_style="carto-positron",
    margin=dict(l=0, r=0, t=50, b=0),
    legend_title_text="Area",
    mapbox_center={
        "lat": filtered_station_activity["lat"].mean(),
        "lon": filtered_station_activity["lng"].mean()
    }
)

st.plotly_chart(fig8, use_container_width=True)

st.markdown(
    """
    This map shows the distribution of station-level activity across Jersey City and Hoboken.
    Larger circles represent higher trip volume, helping identify the major activity centers.
    """
)


st.divider()


st.subheader(f"Chart 9. Top {top_n} Busiest Citi Bike Stations")

top10_stations = (
    filtered_station_activity
    .sort_values(trip_metric, ascending=False)
    .head(top_n)
    .sort_values(trip_metric, ascending=True)
)

fig9 = px.bar(
    top10_stations,
    x=trip_metric,
    y="station_name",
    color="area",
    orientation="h",
    text=trip_metric,
    hover_data={
        "area": True,
        "start_trips": ":,.0f",
        "end_trips": ":,.0f",
        "total_trips": ":,.0f"
    },
    title=f"Chart 9. Top {top_n} Busiest Citi Bike Stations"
)

fig9.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside"
)

fig9.update_layout(
    xaxis_title=trip_metric.replace("_", " ").title(),
    yaxis_title="Station",
    height=max(560, 42 * top_n),
    margin=dict(l=240, r=100, t=50, b=50),
    legend_title_text="Area"
)

st.plotly_chart(fig9, use_container_width=True)

st.markdown(
    """
    This bar chart highlights the busiest stations in the system. These stations are often
    located near major transit nodes, waterfront areas, and dense mixed-use neighborhoods.
    """
)


st.divider()


st.subheader("Chart 10. Area-Level Citi Bike Activity: Jersey City vs Hoboken")

area_activity_sorted = filtered_area_activity.sort_values(
    trip_metric,
    ascending=True
)

fig10 = px.bar(
    area_activity_sorted,
    x=trip_metric,
    y="area",
    orientation="h",
    text=trip_metric,
    hover_data={
        "start_trips": ":,.0f",
        "end_trips": ":,.0f",
        "total_trips": ":,.0f",
        "station_count": ":,.0f"
    },
    title="Chart 10. Area-Level Citi Bike Activity: Jersey City vs Hoboken"
)

fig10.update_traces(
    texttemplate="%{text:,.0f}",
    textposition="outside"
)

fig10.update_layout(
    xaxis_title=trip_metric.replace("_", " ").title(),
    yaxis_title="Area",
    height=420,
    margin=dict(l=140, r=100, t=50, b=50)
)

st.plotly_chart(fig10, use_container_width=True)

st.markdown(
    """
    This area-level comparison shows whether Citi Bike activity is more concentrated
    in Jersey City or Hoboken. This is more appropriate than a NYC borough choropleth
    because the uploaded dataset covers Jersey City / Hoboken rather than the full NYC system.
    """
)


st.divider()


st.subheader("Chart 12. Citi Bike Station Hotspots by Total Trip Volume")

hotspot_stations = filtered_station_activity.copy()

hotspot_stations["hotspot_rank"] = (
    hotspot_stations[trip_metric]
    .rank(method="dense", ascending=False)
)

hotspot_stations["hotspot_group"] = pd.cut(
    hotspot_stations["hotspot_rank"],
    bins=[0, 10, 25, 1000],
    labels=["Top 10 hotspot", "Top 11-25", "Other stations"]
)

fig12 = px.scatter_mapbox(
    hotspot_stations,
    lat="lat",
    lon="lng",
    size=trip_metric,
    color="hotspot_group",
    hover_name="station_name",
    hover_data={
        "area": True,
        "start_trips": ":,.0f",
        "end_trips": ":,.0f",
        "total_trips": ":,.0f",
        "hotspot_rank": ":.0f",
        "lat": False,
        "lng": False
    },
    size_max=38,
    zoom=map_zoom,
    height=700,
    title="Chart 12. Citi Bike Station Hotspots by Total Trip Volume"
)

fig12.update_layout(
    mapbox_style="carto-positron",
    margin=dict(l=0, r=0, t=50, b=0),
    legend_title_text="Hotspot Level",
    mapbox_center={
        "lat": filtered_station_activity["lat"].mean(),
        "lon": filtered_station_activity["lng"].mean()
    }
)

st.plotly_chart(fig12, use_container_width=True)

st.markdown(
    """
    This hotspot map identifies the most important station-level activity centers.
    Compared with a trip-level density map, this bubble map is more readable because
    it directly shows which stations dominate total trip volume.
    """
)


st.divider()


st.subheader("Summary Tables")

tab1, tab2, tab3 = st.tabs(
    [
        "Top Stations",
        "Area Activity",
        "All Station Activity"
    ]
)

with tab1:
    st.dataframe(
        top10_stations[
            [
                "station_name",
                "area",
                "start_trips",
                "end_trips",
                "total_trips"
            ]
        ].sort_values(trip_metric, ascending=False),
        use_container_width=True
    )

with tab2:
    st.dataframe(
        filtered_area_activity.sort_values(trip_metric, ascending=False),
        use_container_width=True
    )

with tab3:
    st.dataframe(
        filtered_station_activity.sort_values(trip_metric, ascending=False),
        use_container_width=True
    )


st.divider()


st.subheader("Interpretation")

top_station = (
    filtered_station_activity
    .sort_values(trip_metric, ascending=False)
    .iloc[0]
)

top_area = (
    filtered_area_activity
    .sort_values(trip_metric, ascending=False)
    .iloc[0]
)

st.markdown(
    f"""
    The spatial pattern indicates that Citi Bike activity is concentrated around major
    transportation and high-density urban nodes in Jersey City and Hoboken.

    Based on the selected metric (**{trip_metric.replace("_", " ")}**), the busiest station is
    **{top_station["station_name"]}**, with **{top_station[trip_metric]:,.0f}** trips.
    At the area level, **{top_area["area"]}** records the highest activity, with
    **{top_area[trip_metric]:,.0f}** trips.

    Overall, the strongest hotspots are associated with transit access, waterfront activity,
    and dense mixed-use neighborhood structure.
    """
)


st.download_button(
    label="Download Station Activity CSV",
    data=filtered_station_activity.to_csv(index=False),
    file_name="station_activity_summary.csv",
    mime="text/csv"
)

st.download_button(
    label="Download Area Activity CSV",
    data=filtered_area_activity.to_csv(index=False),
    file_name="area_activity_summary.csv",
    mime="text/csv"
)
